.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MLVPN\.CONF" "5" "March 2012" "" ""
.
.SH "NAME"
\fBmlvpn\.conf\fR \- MLVPN configuration
.
.SH "DESCRIPTION"
See mlvpn(1) for more info on MLVPN\.
.
.SH "SYNTAX"
mlvpn\.conf(5) is a "ini style" config file\.
.
.P
Sections are surrounded with []\. \fB\fIgeneral\fR\fR for example\.
.
.P
Comments can be inserted anyware, starting with \fB#\fR\.
.
.P
Key / Values are written in plain ascii separated with the "=" character\. Example: loglevel = 4
.
.P
Long strings should be escaped with doublequote\.
.
.SH "SECTIONS"
Mandatory keys are marked with "(*)"\.
.
.SS "GENERAL"
The \fB\fIgeneral\fR\fR sections is reserved by mlvpn(1) for global configuration\.
.
.P
Prameters:
.
.IP "\(bu" 4
(*) statuscommand = "/path/to/secured_updown_script\.sh" This command is launched when mlvpn(1) detects a change:
.
.IP "\(bu" 4
mlvpn(1) \fBTun/Tap\fR interface is ready\.
.
.IP "\(bu" 4
mlvpn(1) \fBTun/Tap\fR interface must be shut down\.
.
.IP "\(bu" 4
mlvpn(1) remote tunnel is up
.
.IP "\(bu" 4
mlvpn(1) remote tunnel is down See the example mlvpn_updown\.sh for more info\.
.
.IP "" 0

.
.IP "\(bu" 4
(*) mode = "client" or "server" mlvpn(1) should act as a socket server or socket client?
.
.IP "\(bu" 4
(*) protocol = "udp" or "tcp" Prefer UDP for better performance\.
.
.IP "\(bu" 4
logfile = "/path/to/mlvpn\.log" Tells MLVPN where to store logfile\.
.
.IP "\(bu" 4
loglevel = 3 Change the log level\. Valid values from \fB1\fR (quiet) to \fB4\fR (debug)
.
.IP "\(bu" 4
timeout = 5 Integer value for detecting "link" timeout\.
.
.IP "\(bu" 4
interface_name = "mlvpn0" Change the \fBTun/Tap\fR interface name\.
.
.IP "" 0
.
.SS " LINKS"
Each link must be declared in it\'s own section\.
.
.P
The section name is the link name\. Example: "[adsl1]", "[adsl2]"\.
.
.P
Parameters:
.
.IP "\(bu" 4
(both) bindhost = "0\.0\.0\.0" Bind on a specific address\. (IPv4 only)
.
.IP "\(bu" 4
(both) bindport = 5080 Bind on a specific port\.
.
.IP "\(bu" 4
(client) remotehost = "1\.2\.3\.4" Where to connect to\.
.
.IP "\(bu" 4
(client) remoteport = 5080
.
.IP "\(bu" 4
(both) bandwidth_upload = 61440 client => server max bandwidth used by mlvpn for this link\. Bandwidth is specified in Bytes (1024 base)\.
.
.IP "\(bu" 4
(both) bandwidth_download = 512000 server => client max bandwidth used by mlvpn for this link\. Bandwidth is specified in Bytes (1024 base)\.
.
.IP "\(bu" 4
(both) timeout = 10 Override \fB\fIgeneral\fR\fR timeout for this link\.
.
.IP "\(bu" 4
(both) protocol = 10 Override \fB\fIgeneral\fR\fR protocol for this link\.
.
.IP "" 0
.
.SH "EXAMPLE"
See examples/mlvpn\.conf
.
.SH "SEE ALSO"
mlvpn\.conf(5)
