.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "MLVPN" "1" "November 2015" "" ""
.
.SH "NAME"
\fBmlvpn\fR \- MultiLink Virtual Public Network aggregator
.
.SH "SYNOPSIS"
\fBmlvpn\fR \-\-user mlvpn \-\-config /path/to/mlvpn\.conf
.
.SH "DESCRIPTION"
\fBmlvpn\fR is designed to help building aggregation tunnels between two hosts\.
.
.P
Main features are:
.
.IP "\(bu" 4
Bandwidth aggregation
.
.IP "\(bu" 4
High availability (detects link up/down)
.
.IP "\(bu" 4
Security (Privilege separation, auth and cipher using libsodium)
.
.IP "\(bu" 4
Scritable
.
.IP "\(bu" 4
External program control (using unix socket or TCP/HTTP socket)
.
.IP "" 0
.
.P
\fBmlvpn\fR uses privilege seperation to increase security\. The monitor process is running as root, doing only privileged operations, the other process is doing most of the stuff\.
.
.P
In order to be able to aggregate multiple links with mismatched bandwidth, \fBmlvpn\fR uses a weight round\-robin algorithm\. \fBmlvpn\fR then sends packets, according to the capacity of the link\. It should be noted that \fBmlvpn\fR only knows about what it sends, so you should ONLY use \fBmlvpn\fR on the links if you want good balancing of the links\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-config\fR, \fB\-c\fR \fIfile\fR
path to the configuration file
.
.TP
\fB\-\-user\fR, \fB\-u\fR \fIusername\fR
drop privileges to \fIusername\fR
.
.TP
\fB\-\-natural\-title\fR
do not use setproctitle(3)
.
.TP
\fB\-\-name\fR, \fB\-n\fR \fIname\fR
change process title to \fIname\fR (privileged process will be named \fIname\fR [priv]: this option is disabled with \fB\-\-natural\-title\fR is used
.
.TP
\fB\-\-debug\fR
log to stderr instead of syslog
.
.TP
\fB\-D\fR\fItoken\fR
only show messages of specified \fItoken\fR\. See README\.debug\.md for available tokens\. \-D can be specified multiple times
.
.TP
\fB\-\-verbose\fR, \fB\-v\fR
increases verbosity (repeat multiple times to increase more)
.
.TP
\fB\-\-quiet\fR, \fB\-q\fR
decrease verbosity The verbosity will print usefull messages and errors only\. If \fB\-\-quiet\fR is specified, then only errors will be shown / logged
.
.TP
\fB\-\-yes\-run\-as\-root\fR
don\'t drop privileges, kills privilege separation, do not use unless you are hacking \fBmlvpn\fR
.
.TP
\fB\-\-version\fR
display the current version of \fBmlvpn\fR
.
.TP
\fB\-h\fR
show the help
.
.SH "LOGGING"
mlvpn uses syslog if \fB\-\-debug\fR is not specified\. if \fB\-\-debug\fR is specified, mlvpn sends logging messages to syslog\.
.
.SH "FILES"
.
.TP
\fI/etc/mlvpn/*\.conf\fR
configuration files for \fBmlvpn\fR
.
.SH "DEBUGGING"
refer to README\.debug\.md for more debugging informations\.
.
.SH "SEE ALSO"
mlvpn\.conf(5)
.
.SH "LINKS"
.
.IP "\(bu" 4
https://github\.com/zehome/MLVPN
.
.IP "\(bu" 4
http://mlvpn\.readthedocs\.org/
.
.IP "" 0
.
.SH "AUTHORS"
.
.IP "\(bu" 4
Laurent Coustet Initial work, current maintainer
.
.IP "" 0

