#!/bin/sh
# Copyright 2001 Alberto Gonzalez Iniesta <agi@agi.as>
# Modified for MLVPN by Laurent Coustet <ed@zehome.com>
# Licensed under the GNU General Public License, version 2.  See the file
# /usr/share/common-licenses/GPL or <http://www.gnu.org/copyleft/gpl.txt>.
#
set -e
test $DEBIAN_SCRIPT_DEBUG && set -v -x

# use debconf
. /usr/share/debconf/confmodule

case "$1" in
  configure)
    # get rid of confiles installed by mistake
    db_get mlvpn/create_tun || RET="false"
    if [ "$RET" = "true" ]; then
      [ -e /dev/net ] || mkdir -m 755 /dev/net
      [ -d /dev/net -a ! -e /dev/net/tun ] && mknod /dev/net/tun c 10 200
    fi
  ;;
esac

if [ -x "/etc/init.d/mlvpn" ]; then
    if [ -x /usr/sbin/invoke-rc.d ]; then
       invoke-rc.d mlvpn cond-restart || invoke-rc.d mlvpn restart
    else
       /etc/init.d/mlvpn cond-restart || /etc/init.d/mlvpn restart
    fi
fi

db_stop

#DEBHELPER#

exit 0
# vim:set ai et sts=2 sw=2 tw=0:
