#!/bin/sh
# Copyright 2004 Alberto Gonzalez Iniesta <agi@agi.as>
# Modified for MLVPN by Laurent Coustet <ed@zehome.com>
# Licensed under the GNU General Public License, version 2.  See the file
# /usr/share/common-licenses/GPL or <http://www.gnu.org/copyleft/gpl.txt>.
#

set -e
test $DEBIAN_SCRIPT_DEBUG && set -v -x

stop_vpn () {
  if [ -x "/etc/init.d/mlvpn" ]; then
          if [ -x /usr/sbin/invoke-rc.d ] ; then
                  invoke-rc.d mlvpn stop
          else
                  /etc/init.d/mlvpn stop
          fi
  fi
}


case "$1" in
  upgrade)
    # don't stop the vpn, it will be restarted after the upgrade
    true
  ;;
  *)
    stop_vpn
  ;;
esac

#DEBHELPER#

exit 0
# vim:set ai et sts=2 sw=2 tw=0:
